### ISSUE TITLE
Potential Semver Minor Backports

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/LTS#177]
These are some possible semver minors I've flagged for potential inclusion in an upcoming semver minor LTS release. **Please feel free to veto any of these** or suggest other from [this gist](https://gist.github.com/MylesBorins/fc37b3bde0e7d2e7c18c7c8b15c133d7). The primary motivation here is that we are going to be doing one more LTS semver minor on v4.x already, and it will likely be the last one. I figured we could take this opportunity to audit and minimize delta on certain features to make support for v4.x less painful during the 12 month Maintenance period.

### Approved

**4.x only:**

- [x] **tls, crypto**: add ALPN Support (Shigeki Ohtsu) [#2564](https://github.com/nodejs/node/pull/2564)
  - requires manual backport
- [x] **process**: add process.cpuUsage() - implementation, doc, tests (Patrick Mueller) [#6157](https://github.com/nodejs/node/pull/6157)
  - pending backport https://github.com/nodejs/node/pull/10796
- [x] **v8,src**: expose statistics about heap spaces (Ben Ripkens) [#4463](https://github.com/nodejs/node/pull/4463)
- [x] **child_process**:  child_process: add shell option to spawn() [#4598](https://github.com/nodejs/node/pull/4598)
- [x] **fs**: add the fs.mkdtemp() function. (Florian MARGAINE) [#5333](https://github.com/nodejs/node/pull/5333)

**6.x only**

- [x] **deps**: Intl: ICU 58 bump - small icu (BIG COMMIT) (Steven R. Loomis) [#9234](https://github.com/nodejs/node/pull/9234)
  - requires manual backport
- [x] **deps**: intl: Add more versions from ICU (Steven R. Loomis) [#9266](https://github.com/nodejs/node/pull/9266)
  - requires manual backport

**4.x and 6.x**

- [ ] **crypto**: crypto: allow adding extra certs to well-known CAs (Sam Roberts) [#9139](https://github.com/nodejs/node/pull/9139)
- [x] **process** add `externalMemory` to process.memoryUsage (indutny) [#9587](https://github.com/nodejs/node/pull/9587)

<details>
<summary>Not Approved</summary>

**4.x only:**

* ~~**net**: add net.listening boolean property over a getter (José Moreira) [#4743](https://github.com/nodejs/node/pull/4743)~~
* ~~**cluster**: support stdio option for workers (cjihrig) [#7838](https://github.com/nodejs/node/pull/7838)~~
* ~~**util**: allow symbol-based custom inspection methods (addaleax) [#9688](https://github.com/nodejs/node/pull/9688/)~~

**6.x only**

* ~~**src,module**: add --preserve-symlinks command line flag (James M Snell) [#6537](https://github.com/nodejs/node/pull/6537)~~

**4.x and 6.x**

* ~~**buffer**: add buffer.transcode (James M Snell) [#9038](https://github.com/nodejs/node/pull/9038)~~
* ~~**child_process**: add public API for IPC channel (cjihrig) [#9322](https://github.com/nodejs/node/pull/9322)~~
</details>

**Comment by Fishrock123** [comment]
Unsure we should backport `--preserve-symlinks`?

**Comment by Fishrock123** [comment]
<details>
<summary>heading title</summary>

// stuff here

</details>

```
<details>
<summary>heading title</summary>

// stuff here

</details>
```

**Comment by Fishrock123** [comment]
Update: We don't use `process.cpuUsage()`. I can ask to see if we can get backport help if desired.

**Comment by MylesBorins** [comment]
@Fishrock123 that details stuff does not appear to work :(

**Comment by addaleax** [comment]
> that details stuff does not appear to work :(

old browser? ;)

**Comment by Fishrock123** [comment]
@MylesBorins you need to put spaces around the tags, i.e. no </summary and then ``` on the next line
