### ISSUE TITLE
Potential Semver Minor Backports

### ISSUE THREAD

**Issue by gibfahn** [nodejs/LTS#188]
Some more semver-minors to consider, now that https://github.com/nodejs/LTS/issues/177 is closed.

## Semver-minor v6.x backports:

I ran ` branch-diff --reverse --filter-release --require-label=semver-minor --exclude-label=semver-major,meta,dont-land-on-v6.x,backport-requested-to-v6.x up/v6.x up/v7.x`

Not sure why it didn't include this (from the [search query](https://github.com/nodejs/node/pulls?q=is%3Apr+is%3Aclosed+label%3Alts-watch-v4.x+label%3Alts-watch-v6.x+label%3Asemver-minor)), maybe because the backport PR has `do-not-land` and didn't have `semver-major`, and the `PR-URL` was changed: 

### Yes

- [x] [[`570c5e1da8`](https://github.com/nodejs/node/commit/570c5e1da8)] - **(SEMVER-MINOR)** **crypto**: support OPENSSL_CONF again (Sam Roberts) [#11006](https://github.com/nodejs/node/pull/11006)
- [x] [[`8be6702539`](https://github.com/nodejs/node/commit/8be6702539)] - **(SEMVER-MINOR)** **src**: add SafeGetenv() to internal API (    Sam Roberts) [#11006](https://github.com/nodejs/node/pull/11006)
- [x] [[`08a7e7b009`](https://github.com/nodejs/node/commit/08a7e7b009)] - **(SEMVER-MINOR)** **crypto**: return `this` in setAuthTag/setAAD (    Kirill Fomichev) [#9398](https://github.com/nodejs/node/pull/9398)
- [x] [[`ac2b059500`](https://github.com/nodejs/node/commit/ac2b059500)] - **(SEMVER-MINOR)** **crypto**: do not use pointers to std::vector (    Adam Majer) [#8334](https://github.com/nodejs/node/pull/8334)
- [x] [[`aeea13b6f6`](https://github.com/nodejs/node/commit/aeea13b6f6)] - **(SEMVER-MINOR)** **crypto**: Use system CAs instead of using bundled ones (    Adam Majer) [#8334](https://github.com/nodejs/node/pull/8334)
- [x] [[`a1897c1445`](https://github.com/nodejs/node/commit/a1897c1445)] - **(SEMVER-MINOR)** **crypto**: ability to select cert store at runtime (    Adam Majer) [#8334](https://github.com/nodejs/node/pull/8334)
- [x] [[`0a3e5cc57a`](https://github.com/nodejs/node/commit/0a3e5cc57a)] - **(SEMVER-MINOR)** **dns**: implement {ttl: true} for dns.resolve6() (    Ben Noordhuis) [#9296](https://github.com/nodejs/node/pull/9296)
- [x] [[`1bd79368cd`](https://github.com/nodejs/node/commit/1bd79368cd)] - **(SEMVER-MINOR)** **dns**: implement {ttl: true} for dns.resolve4() (    Ben Noordhuis) [#9296](https://github.com/nodejs/node/pull/9296)
- [x] [[`663c44eaaa`](https://github.com/nodejs/node/commit/663c44eaaa)] - **(SEMVER-MINOR)** **cluster**: return worker reference from disconnect() (    Sean Villars) [#10019](https://github.com/nodejs/node/pull/10019)
- [x] [[`2096638fe0`](https://github.com/nodejs/node/commit/2096638fe0)] - **(SEMVER-MINOR)** **tls**: allow obvious key/passphrase combinations (    Sam Roberts) [#10294](https://github.com/nodejs/node/pull/10294)
- [x] [[`ecb3a7e933`](https://github.com/nodejs/node/commit/ecb3a7e933)] - **(SEMVER-MINOR)** **test**: make tls-socket-default-options tests run (    Sam Roberts) [#11005](https://github.com/nodejs/node/pull/11005)
- [x] [[`4e327708a9`](https://github.com/nodejs/node/commit/4e327708a9)] - **(SEMVER-MINOR)** **tls**: new tls.TLSSocket() supports sec ctx options (    Sam Roberts) [#11005](https://github.com/nodejs/node/pull/11005)
- [x] [[`d24491c6a7`](https://github.com/nodejs/node/commit/d24491c6a7)] - **(SEMVER-MINOR)** **process**: add NODE_NO_WARNINGS environment variable (    cjihrig) [#10842](https://github.com/nodejs/node/pull/10842)
- [x] [[`92ed2b5001`](https://github.com/nodejs/node/commit/92ed2b5001)] - **(SEMVER-MINOR)** **build**: support for mips64el (    nanxiongchao) [#10991](https://github.com/nodejs/node/pull/10991)
- [x] [[`8ab26cf508`](https://github.com/nodejs/node/commit/8ab26cf508)] - **(SEMVER-MINOR)** **readline**: add option to stop duplicates in history (    Danny Nemer) [#2982](https://github.com/nodejs/node/pull/2982)
- [ ] [[`ffd938a694`](https://github.com/nodejs/node/commit/ffd938a694)] - **(SEMVER-MINOR)** **deps**: upgrade libuv to 1.10.2 (cjihrig) [#10717](https://github.com/nodejs/node/pull/10717)
  - [ ] [[`786631c7b4`](https://github.com/nodejs/node/commit/786631c7b4)] - **(SEMVER-MINOR)** **deps**: upgrade libuv to 1.10.1 (cjihrig) [#9647](https://github.com/nodejs/node/pull/9647)
  - [ ] [[`106d71914c`](https://github.com/nodejs/node/commit/106d71914c)] - **(SEMVER-MINOR)** **deps**: upgrade libuv to 1.10.0 (cjihrig) [#9267](https://github.com/nodejs/node/pull/9267)

### Manual

- [ ] **http:** add new functions to OutgoingMessage https://github.com/nodejs/node/pull/10805 (backported in https://github.com/nodejs/node/pull/11562)

#### Don't need backporting:

- [x] [[`3596d156c1`](https://github.com/nodejs/node/commit/3596d156c1)] - **(SEMVER-MINOR)** **lib**: build `node inspect` into `node` (    Anna Henningsen) [#10187](https://github.com/nodejs/node/pull/10187)
- [x] [[`85f54908bf`](https://github.com/nodejs/node/commit/85f54908bf)] - **(SEMVER-MINOR)** **deps**: add node-inspect 1.10.2 (Jan Krems) [#10187](https://github.com/nodejs/node/pull/10187)
- [x] [[`b1ef638de3`](https://github.com/nodejs/node/commit/b1ef638de3)] - **(SEMVER-MINOR)** **src**: default --icu_case_mapping on as a v8 option (    Steven R. Loomis) [#9454](https://github.com/nodejs/node/pull/9454)
- [x] [[`8fdfa08ed0`](https://github.com/nodejs/node/commit/8fdfa08ed0)] - **(SEMVER-MINOR)** **build**: add node-inspect integration test (Jan Krems) [#10187](https://github.com/nodejs/node/pull/10187)
- [x] [[`84e2ff3738`](https://github.com/nodejs/node/commit/84e2ff3738)] - **(SEMVER-MINOR)** **doc**: add basic documentation for WHATWG URL API (James M Snell) [#10620](https://github.com/nodejs/node/pull/10620)
- [x] [[`614742b67f`](https://github.com/nodejs/node/commit/614742b67f)] - **(SEMVER-MINOR)** **lib**: deprecate node --debug at runtime (    Josh Gavant) [#11275](https://github.com/nodejs/node/pull/11275)
- [x] [[`614742b67f`](https://github.com/nodejs/node/commit/614742b67f)] - **(SEMVER-MINOR)** **lib**: deprecate node --debug at runtime (Josh Gavant) [#11275](https://github.com/nodejs/node/pull/11275)
- [x] [[`c92b8ecd81`](https://github.com/nodejs/node/commit/c92b8ecd81)] - **(SEMVER-MINOR)** **tools**: add mdn link for Iterator (    James M Snell) [#10620](https://github.com/nodejs/node/pull/10620)
- [x] [[`84e2ff3738`](https://github.com/nodejs/node/commit/84e2ff3738)] - **(SEMVER-MINOR)** **doc**: add basic documentation for WHATWG URL API (    James M Snell) [#10620](https://github.com/nodejs/node/pull/10620)
- [x] [[`a5c62cb4f2`](https://github.com/nodejs/node/commit/a5c62cb4f2)] - **(SEMVER-MINOR)** **readline**: use icu based string width calculation (    James M Snell) [#9040](https://github.com/nodejs/node/pull/9040)

#### Unsorted:

- [ ] [[`1ee38eb874`](https://github.com/nodejs/node/commit/1ee38eb874)] - **(SEMVER-MINOR)** **util**: add %i and %f formatting specifiers (    Roman Reiss) [#10308](https://github.com/nodejs/node/pull/10308)
- [ ] [[`75f4329e01`](https://github.com/nodejs/node/commit/75f4329e01)] - **(SEMVER-MINOR)** **crypto**: add randomFill and randomFillSync (    Evan Lucas) [#10209](https://github.com/nodejs/node/pull/10209)

**Comment by mhdawson** [comment]
I'm thinking one last one as it transitions to maintenance would make sense.

**Comment by sam-github** [comment]
#8334 would probably be appreciated by the distros that use it, and which will be maintaining 4.x for some time, though they may be cherry picking the change anyhow.

The tls, src, and http will make writing portable code across LTS versions much easier.

**Comment by italoacasas** [comment]
Those commits have been living in `v7.x` for at least 4 weeks. `Just as general information`

**Comment by gibfahn** [comment]
We also need to make sure we discuss the zlib update (https://github.com/nodejs/node/pull/10980), see https://github.com/nodejs/node/pull/10980#issuecomment-288148106

**Comment by MylesBorins** [comment]
I went ahead and landed the zlib updates in staging. I think them not landing was an oversight. If anyone can think of any reasons to pull it we can do so and discuss

**Comment by MylesBorins** [comment]
Also worth mentioning we will not be doing any more minors on v4.x, so we can focus on v6.x

**Comment by sam-github** [comment]
If someone adds me to the repo I can edit - in the meantime, @gibfahn , can you add to 8334 a ref to it's 6.x backport: https://github.com/nodejs/node/pull/11794

**Comment by gibfahn** [comment]
I'm not sure how patches to v4.x get discussed, but it makes sense (at least to me) to raise them for discussion in the same way we currently discuss semver-minor backports to Active LTS. 

For example, I was looking through some old testcase failures, and I noticed that https://github.com/nodejs/node/pull/10212 wasn't backported to v4.x. This is something we've seen fail quite a few times in v4.x, so it _might_ be worth considering it for backporting.

**Comment by MylesBorins** [comment]
@gibfahn do you want to update this list before the meeting tomorrow?

**Comment by jasnell** [comment]
#11220 should not be backported to any LTS branch.

**Comment by jasnell** [comment]
Nor should https://github.com/nodejs/node/pull/10739

**Comment by sam-github** [comment]
I missed end of meeting, but: #10209 might need baking, but should backport for consistency

**Comment by MylesBorins** [comment]
@sam-github that was discussed and the conclusion in the meeting

**Comment by gibfahn** [comment]
@MylesBorins I think everything here is done and this can be closed now (reopen if you agree...)
