### ISSUE TITLE
Backporting to v6.x-staging

### ISSUE THREAD

**Issue by gibfahn** [nodejs/LTS#216]
Comment if you start or stop backporting.

Working from [this gist](https://gist.github.com/MylesBorins/18387d4b8a858ace83122ef9b88d2e5b)

List generated from this command:
`branch-diff v6.x-staging upstream/v7.x --exclude-label semver-major,semver-minor,dont-land-on-v6.x,backport-requested-v6.x,backported-to-v6.x,baking-for-lts --reverse --filter-release
Raw
`

Labels information in https://github.com/nodejs/node/pull/12431

### Commits to backport:

Ticked means looked at

- [x] [[`f5a702e763`](https://github.com/nodejs/node/commit/f5a702e763)] - **stream**: Fixes missing 'unpipe' event (Christopher Luke) [#11876](https://github.com/nodejs/node/pull/11876) => v7.x backport cherry-picks cleanly, PR depends on https://github.com/nodejs/node/pull/11152
- [x] [[`592db37e2f`](https://github.com/nodejs/node/commit/592db37e2f)] - **test**: move test to sequential for reliability (Rich Trott) [#12704](https://github.com/nodejs/node/pull/12704) => should land
- [x] [[`c2c62874d4`](https://github.com/nodejs/node/commit/c2c62874d4)] - **doc**: fix formatting of TOC (Refael Ackermann) [#12731](https://github.com/nodejs/node/pull/12731) => should land
- [x] [[`7af2e7940c`](https://github.com/nodejs/node/commit/7af2e7940c)] - **test**: fix permanent deoptimizations (Brian White) [#12456](https://github.com/nodejs/node/pull/12456) => asked on PR
  - [x] [[`1ac331b29f`](https://github.com/nodejs/node/commit/1ac331b29f)] - **readline**: fix permanent deoptimizations (Brian White) [#12456](https://github.com/nodejs/node/pull/12456)
  - [x] [[`4a082889bd`](https://github.com/nodejs/node/commit/4a082889bd)] - **net**: fix permanent deoptimizations (Brian White) [#12456](https://github.com/nodejs/node/pull/12456)
  - [x] [[`b573f77b28`](https://github.com/nodejs/node/commit/b573f77b28)] - **process**: fix permanent deoptimizations (Brian White) [#12456](https://github.com/nodejs/node/pull/12456)
  - [x] [[`933b6b57d6`](https://github.com/nodejs/node/commit/933b6b57d6)] - **cluster**: fix permanent deoptimizations (Brian White) [#12456](https://github.com/nodejs/node/pull/12456)
  - [x] [[`84484b7063`](https://github.com/nodejs/node/commit/84484b7063)] - **fs**: fix permanent deoptimizations (Brian White) [#12456](https://github.com/nodejs/node/pull/12456)
  - [x] [[`7d0adc6d26`](https://github.com/nodejs/node/commit/7d0adc6d26)] - **stream**: fix permanent deoptimizations (Brian White) [#12456](https://github.com/nodejs/node/pull/12456)
  - [x] [[`caf6506f9f`](https://github.com/nodejs/node/commit/caf6506f9f)] - **build**: add target for checking for perm deopts (Brian White) [#12456](https://github.com/nodejs/node/pull/12456)
  - [x] [[`9da719ab32`](https://github.com/nodejs/node/commit/9da719ab32)] - **test**: fix test filenames (Brian White) [#12456](https://github.com/nodejs/node/pull/12456)
- [x] [[`cd54208463`](https://github.com/nodejs/node/commit/cd54208463)] - **process**: cast promise rejection reason to string (Cameron Little) [#11640](https://github.com/nodejs/node/pull/11640) => asked on PR
  - [x] [[`d78adccc08`](https://github.com/nodejs/node/commit/d78adccc08)] - **test**: support multiple warnings in checkWarning (Cameron Little) [#11640](https://github.com/nodejs/node/pull/11640)
- [x] [[`f60a2e9527`](https://github.com/nodejs/node/commit/f60a2e9527)] - **doc**: fixup the collaborators list (Alexey Orlenko) [#12750](https://github.com/nodejs/node/pull/12750) => landed
- [x] [[`819c131f58`](https://github.com/nodejs/node/commit/819c131f58)] - **test**: improve test-tcp-wrap-listen (alohaglenn) [#12599](https://github.com/nodejs/node/pull/12599) => conflicts, could be backported
- [x] [[`90bba9fd3e`](https://github.com/nodejs/node/commit/90bba9fd3e)] - **test,doc**: document `crashOnUnhandledRejection()` (Anna Henningsen) [#12699](https://github.com/nodejs/node/pull/12699) => dont land, docs a non-existent function
- [x] [[`224fd3af97`](https://github.com/nodejs/node/commit/224fd3af97)] - **benchmark**: terminate child process on Windows (Rich Trott) [#12658](https://github.com/nodejs/node/pull/12658)
- [x] [[`360efe48bc`](https://github.com/nodejs/node/commit/360efe48bc)] - **doc**: fix examples in repl.md (Vse Mozhet Byt) [#12684](https://github.com/nodejs/node/pull/12684)
- [x] [[`395380a136`](https://github.com/nodejs/node/commit/395380a136)] - **doc**: add Added-in metadata for WHATWG URL (Timothy Gu) [#12683](https://github.com/nodejs/node/pull/12683)
  - [x] [[`fc96d1a573`](https://github.com/nodejs/node/commit/fc96d1a573)] - **doc**: document url.domainTo* methods separately (Timothy Gu) [#12683](https://github.com/nodejs/node/pull/12683)
- [x] [[`79dff99428`](https://github.com/nodejs/node/commit/79dff99428)] - **test**: remove eslint comments from test-util.js (cjihrig) [#12669](https://github.com/nodejs/node/pull/12669)
  - [x] [[`dd1dced4c1`](https://github.com/nodejs/node/commit/dd1dced4c1)] - **test**: remove eslint comments (cjihrig) [#12669](https://github.com/nodejs/node/pull/12669)
- [x] [[`3e9e6afd8a`](https://github.com/nodejs/node/commit/3e9e6afd8a)] - **test**: use common.mustCall in test-https-strict (weewey) [#12668](https://github.com/nodejs/node/pull/12668)
- [x] [[`75e053be39`](https://github.com/nodejs/node/commit/75e053be39)] - **test**: cleanup test-util-inherits.js (RobotMermaid) [#12602](https://github.com/nodejs/node/pull/12602)
- [x] [[`212475b451`](https://github.com/nodejs/node/commit/212475b451)] - **build**: use do_not_edit variable where possible (Ruslan Bekenev) [#12610](https://github.com/nodejs/node/pull/12610)
- [x] [[`745dea994e`](https://github.com/nodejs/node/commit/745dea994e)] - **test**: use common.js to check platform (Ruslan Bekenev) [#12629](https://github.com/nodejs/node/pull/12629)
- [x] [[`d154aafe18`](https://github.com/nodejs/node/commit/d154aafe18)] - **deps**: remove **/node_modules/form-data/README.md (Jeremiah Senkpiel) [#12643](https://github.com/nodejs/node/pull/12643)
- [x] [[`8e6d4402a0`](https://github.com/nodejs/node/commit/8e6d4402a0)] - **test**: improve test-process-kill-pid (alohaglenn) [#12588](https://github.com/nodejs/node/pull/12588)
- [x] [[`660e58c7eb`](https://github.com/nodejs/node/commit/660e58c7eb)] - **test**: improved type checking with regex (coreybeaumont) [#12591](https://github.com/nodejs/node/pull/12591)
- [x] [[`e36a256c6b`](https://github.com/nodejs/node/commit/e36a256c6b)] - **test**: cleanup test-fs-watch.js (RobotMermaid) [#12595](https://github.com/nodejs/node/pull/12595)
- [x] [[`d15b1c4446`](https://github.com/nodejs/node/commit/d15b1c4446)] - **test**: add mustCall in test-timers-clearImmediate (Zahidul Islam) [#12598](https://github.com/nodejs/node/pull/12598)
- [x] [[`46a7c297d3`](https://github.com/nodejs/node/commit/46a7c297d3)] - **tools**: use no-useless-concat ESLint rule (Vse Mozhet Byt) [#12613](https://github.com/nodejs/node/pull/12613)
- [x] [[`45facc8822`](https://github.com/nodejs/node/commit/45facc8822)] - **doc**: fix an unclear wording in readline.md (Vse Mozhet Byt) [#12605](https://github.com/nodejs/node/pull/12605)
- [x] [[`da01ff7507`](https://github.com/nodejs/node/commit/da01ff7507)] - **src**: remove invalid comment (cjihrig) [#12645](https://github.com/nodejs/node/pull/12645)
- [x] [[`1316c77b79`](https://github.com/nodejs/node/commit/1316c77b79)] - **doc**: improve randomfill and fix broken link (Sakthipriyan Vairamani (thefourtheye)) [#12541](https://github.com/nodejs/node/pull/12541)
- [x] [[`744ed9477b`](https://github.com/nodejs/node/commit/744ed9477b)] - **src**: expose V8's IsNativeError() in util bindings (cjihrig) [#12546](https://github.com/nodejs/node/pull/12546)
- [x] [[`51eafe8f3c`](https://github.com/nodejs/node/commit/51eafe8f3c)] - **meta**: update authors list (Aashil Patel) [#11533](https://github.com/nodejs/node/pull/11533)
- [x] [[`258eeaa519`](https://github.com/nodejs/node/commit/258eeaa519)] - **tools**: enable no-useless-return eslint rule (cjihrig) [#12577](https://github.com/nodejs/node/pull/12577)
- [x] [[`313b205834`](https://github.com/nodejs/node/commit/313b205834)] - **doc**: prepare js code for eslint-plugin-markdown (Vse Mozhet Byt) [#12563](https://github.com/nodejs/node/pull/12563)
- [x] [[`cbdf9a90d1`](https://github.com/nodejs/node/commit/cbdf9a90d1)] - **lib**: fix typo in comments in module.js (WORMSS) [#12528](https://github.com/nodejs/node/pull/12528)
- [x] [[`989d344ba9`](https://github.com/nodejs/node/commit/989d344ba9)] - **test**: use block scoped variable names (Neehar Venugopal) [#12544](https://github.com/nodejs/node/pull/12544)
- [x] [[`b82e0769fe`](https://github.com/nodejs/node/commit/b82e0769fe)] - **test**: dynamic port in cluster eaddrinuse (Sebastian Plesciuc) [#12547](https://github.com/nodejs/node/pull/12547)
- [x] [[`8ae5afe2d2`](https://github.com/nodejs/node/commit/8ae5afe2d2)] - **test**: dynamic port in cluster ipc throw (Sebastian Plesciuc) [#12571](https://github.com/nodejs/node/pull/12571)
- [x] [[`539ffaef83`](https://github.com/nodejs/node/commit/539ffaef83)] - **url**: improve descriptiveness of identifier (Rich Trott) [#12579](https://github.com/nodejs/node/pull/12579)
- [x] [[`80ceb04644`](https://github.com/nodejs/node/commit/80ceb04644)] - **test**: replace assertion error check with regex (thelady) [#12603](https://github.com/nodejs/node/pull/12603)
- [x] [[`2021ea1c12`](https://github.com/nodejs/node/commit/2021ea1c12)] - **test**: refactored context type err message to regex (Muhsin Abdul-Musawwir) [#12596](https://github.com/nodejs/node/pull/12596)
- [x] [[`1a4bf431fc`](https://github.com/nodejs/node/commit/1a4bf431fc)] - **test**: improve test-process-chdir (vperezma) [#12589](https://github.com/nodejs/node/pull/12589)
- [x] [[`14e93f6369`](https://github.com/nodejs/node/commit/14e93f6369)] - **test**: dynamic port in parallel cluster tests (Sebastian Plesciuc) [#12584](https://github.com/nodejs/node/pull/12584)
- [x] [[`d10eb83325`](https://github.com/nodejs/node/commit/d10eb83325)] - **test**: remove flaky designation for test on AIX (Rich Trott) [#12564](https://github.com/nodejs/node/pull/12564)
- [x] [[`200e899cc4`](https://github.com/nodejs/node/commit/200e899cc4)] - **tools**: add `root: true` in main .eslintrc.yaml (Vse Mozhet Byt) [#12570](https://github.com/nodejs/node/pull/12570)
- [x] [[`b52f77df43`](https://github.com/nodejs/node/commit/b52f77df43)] - **doc**: fix typo in doc/api/process.md (morrme) [#12612](https://github.com/nodejs/node/pull/12612)
- [x] [[`08951a1307`](https://github.com/nodejs/node/commit/08951a1307)] - **src**: replace IsConstructCalls with lambda (Daniel Bevenius) [#12533](https://github.com/nodejs/node/pull/12533)
- [x] [[`f0b5afe721`](https://github.com/nodejs/node/commit/f0b5afe721)] - **test**: dynamic port in cluster worker dgram (Sebastian Plesciuc) [#12487](https://github.com/nodejs/node/pull/12487)
- [x] [[`47b39928d5`](https://github.com/nodejs/node/commit/47b39928d5)] - **doc**: make commit guidelines easier to reference (Benjamin Fleischer) [#11732](https://github.com/nodejs/node/pull/11732)
- [x] [[`661ff6dae3`](https://github.com/nodejs/node/commit/661ff6dae3)] - **test**: move test-debugger-repeat-last to sequential (kumarrishav) [#12470](https://github.com/nodejs/node/pull/12470)
- [x] [[`184941ef0b`](https://github.com/nodejs/node/commit/184941ef0b)] - **src**: remove TODO about uv errno removal (Daniel Bevenius) [#12536](https://github.com/nodejs/node/pull/12536)
- [x] [[`4276c213f2`](https://github.com/nodejs/node/commit/4276c213f2)] - **doc**: add suggestion to use --3way (Michael Dawson) [#12510](https://github.com/nodejs/node/pull/12510)
- [x] [[`0fb69de277`](https://github.com/nodejs/node/commit/0fb69de277)] - **test**: use duplex streams in duplex stream test (cjihrig) [#12514](https://github.com/nodejs/node/pull/12514)
- [x] [[`78ac637fe2`](https://github.com/nodejs/node/commit/78ac637fe2)] - **build**: fix case in lib names (Refael Ackermann) [#12522](https://github.com/nodejs/node/pull/12522)
- [x] [[`f84a5e19b7`](https://github.com/nodejs/node/commit/f84a5e19b7)] - **test**: use JSON.stringify to trigger stack overflow (Yang Guo) [#12481](https://github.com/nodejs/node/pull/12481)
- [x] [[`e77f1e2177`](https://github.com/nodejs/node/commit/e77f1e2177)] - **v8**: fix stack overflow in recursive method (Ben Noordhuis) [#12460](https://github.com/nodejs/node/pull/12460)
- [x] [[`96b2faa79b`](https://github.com/nodejs/node/commit/96b2faa79b)] - **test**: fix parallel/test-setproctitle.js on alpine (David Cai) [#12413](https://github.com/nodejs/node/pull/12413)
- [x] [[`e3ccc3109c`](https://github.com/nodejs/node/commit/e3ccc3109c)] - **test**: set benchmark-child-process flaky on windows (Rich Trott) [#12561](https://github.com/nodejs/node/pull/12561)
- [x] [[`3703fc6bbe`](https://github.com/nodejs/node/commit/3703fc6bbe)] - **doc**: update link to Code of Conduct (Alex Autem) [#12552](https://github.com/nodejs/node/pull/12552)
- [x] [[`434873d24b`](https://github.com/nodejs/node/commit/434873d24b)] - **doc**: fix typo in fs.watch() description (Ivo von Putzer Reibegg) [#12550](https://github.com/nodejs/node/pull/12550)
- [x] [[`eb78722922`](https://github.com/nodejs/node/commit/eb78722922)] - **doc**: add lucamaraschi to collaborators (Luca Maraschi) [#12538](https://github.com/nodejs/node/pull/12538)
- [x] [[`b09bf51cdf`](https://github.com/nodejs/node/commit/b09bf51cdf)] - **repl**: support hidden history file on Windows (Bartosz Sosnowski) [#12207](https://github.com/nodejs/node/pull/12207)
- [x] [[`7d87edc1ba`](https://github.com/nodejs/node/commit/7d87edc1ba)] - **benchmark**: add benchmark for string concatenations (Vse Mozhet Byt) [#12455](https://github.com/nodejs/node/pull/12455)
- [x] [[`08ba9d437c`](https://github.com/nodejs/node/commit/08ba9d437c)] - **benchmark**: fix CLI arguments check in common.js (Vse Mozhet Byt) [#12429](https://github.com/nodejs/node/pull/12429)
- [x] [[`37261319d6`](https://github.com/nodejs/node/commit/37261319d6)] - **test**: minimize time for child_process benchmark (Rich Trott) [#12518](https://github.com/nodejs/node/pull/12518)
- [x] [[`eac0d70429`](https://github.com/nodejs/node/commit/eac0d70429)] - **test**: console.log removed from test-net-localport (Faiz Halde) [#12483](https://github.com/nodejs/node/pull/12483)
- [x] [[`a213320745`](https://github.com/nodejs/node/commit/a213320745)] - **test**: dynamic port in cluster worker disconnect (Sebastian Plesciuc) [#12457](https://github.com/nodejs/node/pull/12457)
- [x] [[`ddc35282c0`](https://github.com/nodejs/node/commit/ddc35282c0)] - **test**: remove uses of common.PORT in test-tls-client tests (Ahmed Taj elsir) [#12461](https://github.com/nodejs/node/pull/12461)
- [x] [[`13441eb1e1`](https://github.com/nodejs/node/commit/13441eb1e1)] - **tools**: add table parsing capability to the doctool (Roman Reiss) [#9532](https://github.com/nodejs/node/pull/9532)
- [x] [[`9250f02d12`](https://github.com/nodejs/node/commit/9250f02d12)] - **doc**: clarify the callback arguments of dns.resolve (Roman Reiss) [#9532](https://github.com/nodejs/node/pull/9532)
- [x] [[`f48d06c042`](https://github.com/nodejs/node/commit/f48d06c042)] - **test**: dynamic port in cluster worker send (Sebastian Plesciuc) [#12472](https://github.com/nodejs/node/pull/12472)
- [x] [[`a75fbe024a`](https://github.com/nodejs/node/commit/a75fbe024a)] - **test**: increase coverage for buffer.js (Rich Trott) [#12476](https://github.com/nodejs/node/pull/12476)
- [x] [[`38278db9c7`](https://github.com/nodejs/node/commit/38278db9c7)] - **doc**: unify spaces in a querystring.md code example (Vse Mozhet Byt) [#12465](https://github.com/nodejs/node/pull/12465)
- [x] [[`e919941a21`](https://github.com/nodejs/node/commit/e919941a21)] - **test**: add test for child_process benchmark (Joyee Cheung) [#12326](https://github.com/nodejs/node/pull/12326)
- [x] [[`8e3d54aca5`](https://github.com/nodejs/node/commit/8e3d54aca5)] - **test**: complete coverage of lib/child_process.js (cjihrig) [#12367](https://github.com/nodejs/node/pull/12367)
- [x] [[`922c457365`](https://github.com/nodejs/node/commit/922c457365)] - **test**: buffer should always be stringified (Luca Maraschi) [#12355](https://github.com/nodejs/node/pull/12355)
- [x] [[`db585c9b4d`](https://github.com/nodejs/node/commit/db585c9b4d)] - **crypto**: update root certificates (Ben Noordhuis) [#12402](https://github.com/nodejs/node/pull/12402)
- [x] [[`3c8e366c2a`](https://github.com/nodejs/node/commit/3c8e366c2a)] - **tools**: update certdata.txt (Ben Noordhuis) [#12402](https://github.com/nodejs/node/pull/12402)
- [x] [[`6003958872`](https://github.com/nodejs/node/commit/6003958872)] - **tools**: add compile_commands.json gyp generator (Ben Noordhuis) [#12450](https://github.com/nodejs/node/pull/12450)
- [x] [[`83a28eeff8`](https://github.com/nodejs/node/commit/83a28eeff8)] - **tools**: update gyp to eb296f6 (Refael Ackermann) [#12450](https://github.com/nodejs/node/pull/12450)
- [x] [[`3fc25dce82`](https://github.com/nodejs/node/commit/3fc25dce82)] - **doc**: run tests before landing changes (Rich Trott) [#12416](https://github.com/nodejs/node/pull/12416)
- [x] [[`af0067cc5e`](https://github.com/nodejs/node/commit/af0067cc5e)] - **doc**: avoid colloquialism (Rich Trott) [#12417](https://github.com/nodejs/node/pull/12417)
- [x] [[`611c23cca6`](https://github.com/nodejs/node/commit/611c23cca6)] - **test**: use dynamic port in test-cluster-bind-twice (Rich Trott) [#12418](https://github.com/nodejs/node/pull/12418)
- [x] [[`a7e13e012d`](https://github.com/nodejs/node/commit/a7e13e012d)] - **test**: remove common.PORT from test-cluster*.js (Tarun Batra) [#12441](https://github.com/nodejs/node/pull/12441)
- [x] [[`d0ba631efa`](https://github.com/nodejs/node/commit/d0ba631efa)] - **doc**: fix encoding string in buffer example (MapleUncle) [#12482](https://github.com/nodejs/node/pull/12482)
- [x] [[`a34cccceaa`](https://github.com/nodejs/node/commit/a34cccceaa)] - **test**: use dynamic port in 3 test-cluster-worker tests (Sebastian Plesciuc) [#12443](https://github.com/nodejs/node/pull/12443)
- [x] [[`3d8878c592`](https://github.com/nodejs/node/commit/3d8878c592)] - **doc**: correct git fix whitespace command (Mateusz Konieczny) [#12445](https://github.com/nodejs/node/pull/12445)
- [x] [[`320b80b792`](https://github.com/nodejs/node/commit/320b80b792)] - **test**: add --use-bundled-ca to tls-cnnic-whitelist (Daniel Bevenius) [#12394](https://github.com/nodejs/node/pull/12394)
- [x] [[`8ac387be3e`](https://github.com/nodejs/node/commit/8ac387be3e)] - **net**: refactor onSlaveClose in Server.close (Claudio Rodriguez) [#12334](https://github.com/nodejs/node/pull/12334)
- [x] [[`440f4d4eef`](https://github.com/nodejs/node/commit/440f4d4eef)] - ***Revert*** "**benchmark**: fix CLI arguments check in common.js" (James M Snell) [#12474](https://github.com/nodejs/node/pull/12474)
- [x] [[`b7aeed7a7e`](https://github.com/nodejs/node/commit/b7aeed7a7e)] - **benchmark**: improve cli error message (Brian White) [#12421](https://github.com/nodejs/node/pull/12421)
- [x] [[`e6be4b951a`](https://github.com/nodejs/node/commit/e6be4b951a)] - **build**: make linter targets silent (Sakthipriyan Vairamani (thefourtheye)) [#12423](https://github.com/nodejs/node/pull/12423)
- [x] [[`917534d541`](https://github.com/nodejs/node/commit/917534d541)] - **benchmark**: fix CLI arguments check in common.js (Vse Mozhet Byt) [#12429](https://github.com/nodejs/node/pull/12429)
- [x] [[`077187e9a8`](https://github.com/nodejs/node/commit/077187e9a8)] - **doc**: s/origin/upstream/ collaborator guide (Anna Henningsen) [#12436](https://github.com/nodejs/node/pull/12436)
- [x] [[`3c59d87164`](https://github.com/nodejs/node/commit/3c59d87164)] - **test**: add crypto check to crypto-lazy-transform (Daniel Bevenius) [#12424](https://github.com/nodejs/node/pull/12424)
- [x] [[`5a2d358f2e`](https://github.com/nodejs/node/commit/5a2d358f2e)] - **doc**: remove inspector experimental warning (cjihrig) [#12408](https://github.com/nodejs/node/pull/12408)
- [x] [[`2e3813f730`](https://github.com/nodejs/node/commit/2e3813f730)] - **meta**: move the Code of Conduct to TSC repository (James M Snell) [#12147](https://github.com/nodejs/node/pull/12147)
- [x] [[`320e72b32d`](https://github.com/nodejs/node/commit/320e72b32d)] - **doc**: add missing ) in CONTRIBUTING.md (Mateusz Konieczny) [#12444](https://github.com/nodejs/node/pull/12444)
- [x] [[`0f290f2414`](https://github.com/nodejs/node/commit/0f290f2414)] - **test**: enable setuid/setgid test (Rich Trott) [#12403](https://github.com/nodejs/node/pull/12403)
- [x] [[`4570d9853c`](https://github.com/nodejs/node/commit/4570d9853c)] - **doc**: add guide for backporting prs (Evan Lucas) [#11099](https://github.com/nodejs/node/pull/11099)
- [x] [[`d7d1e923ad`](https://github.com/nodejs/node/commit/d7d1e923ad)] - **doc**: update link for landing PRs (Rich Trott) [#12415](https://github.com/nodejs/node/pull/12415)
- [x] [[`4a19062294`](https://github.com/nodejs/node/commit/4a19062294)] - **test**: replace \[\].join() with ''.repeat() (Jackson Tian) [#12305](https://github.com/nodejs/node/pull/12305)
- [x] [[`4ce58bd56a`](https://github.com/nodejs/node/commit/4ce58bd56a)] - **doc**: add DavidCai1993 to collaborators (David Cai) [#12435](https://github.com/nodejs/node/pull/12435)
- [x] [[`984232cc2a`](https://github.com/nodejs/node/commit/984232cc2a)] - **doc**: fix typo in streams.md (John Paul Bamberg) [#12428](https://github.com/nodejs/node/pull/12428)
- [x] [[`060b63e91f`](https://github.com/nodejs/node/commit/060b63e91f)] - **doc**: add jkrems to collaborators (Jan Krems) [#12427](https://github.com/nodejs/node/pull/12427)
- [x] [[`5ed9ed3317`](https://github.com/nodejs/node/commit/5ed9ed3317)] - **test**: remove common.PORT from test-cluster-basic (Rich Trott) [#12377](https://github.com/nodejs/node/pull/12377)
- [x] [[`e4b2f61fb5`](https://github.com/nodejs/node/commit/e4b2f61fb5)] - **buffer**: use slightly faster NaN check (Brian White) [#12286](https://github.com/nodejs/node/pull/12286)
- [x] [[`6a45be2fa6`](https://github.com/nodejs/node/commit/6a45be2fa6)] - **doc**: path functions ignore trailing slashes (Tobias Nießen) [#12181](https://github.com/nodejs/node/pull/12181)
- [x] [[`0661fdf781`](https://github.com/nodejs/node/commit/0661fdf781)] - **test**: add test-benchmark-crypto (Rich Trott) [#12347](https://github.com/nodejs/node/pull/12347)
- [x] [[`6998e8026b`](https://github.com/nodejs/node/commit/6998e8026b)] - **os,vm**: fix segfaults and CHECK failure (Tobias Nießen) [#12371](https://github.com/nodejs/node/pull/12371)
- [x] [[`92e239d001`](https://github.com/nodejs/node/commit/92e239d001)] - **doc**: add info about serializable types (Shubheksha Jalan) [#12313](https://github.com/nodejs/node/pull/12313)
- [x] [[`5c57feaa27`](https://github.com/nodejs/node/commit/5c57feaa27)] - **doc**: fix formatting in onboarding-extras (Rich Trott) [#12350](https://github.com/nodejs/node/pull/12350)
- [x] [[`092c7239ee`](https://github.com/nodejs/node/commit/092c7239ee)] - **test**: add hasCrypto check to test-debug-usage (Daniel Bevenius) [#12357](https://github.com/nodejs/node/pull/12357)
- [x] [[`ebeb6c0a26`](https://github.com/nodejs/node/commit/ebeb6c0a26)] - **buffer**: optimize write() (Brian White) [#12361](https://github.com/nodejs/node/pull/12361)
- [x] [[`4d9e6718f8`](https://github.com/nodejs/node/commit/4d9e6718f8)] - **build**: run cpplint even if jslint failed (Ruslan Bekenev) [#12276](https://github.com/nodejs/node/pull/12276)
- [x] [[`e2d66ab809`](https://github.com/nodejs/node/commit/e2d66ab809)] - **doc**: response.write ignores body in some cases (Ruslan Bekenev) [#12314](https://github.com/nodejs/node/pull/12314)
- [x] [[`d1e1832398`](https://github.com/nodejs/node/commit/d1e1832398)] - **doc**: add AnnaMag to collaborators (AnnaMag) [#12414](https://github.com/nodejs/node/pull/12414)
- [x] [[`8ac8e50a58`](https://github.com/nodejs/node/commit/8ac8e50a58)] - **crypto**: make LazyTransform compabile with Streams1 (Matteo Collina) [#12380](https://github.com/nodejs/node/pull/12380)
- [x] [[`d58fa7873f`](https://github.com/nodejs/node/commit/d58fa7873f)] - **benchmark,windows**: TCP.readStart() meaningful only after completion (Refael Ackermann) [#12258](https://github.com/nodejs/node/pull/12258)
- [x] [[`f3db9a6437`](https://github.com/nodejs/node/commit/f3db9a6437)] - **doc**: limit lines to 80 cols in internal README (Evan Lucas) [#12358](https://github.com/nodejs/node/pull/12358)
- [x] [[`aff0cfc2d7`](https://github.com/nodejs/node/commit/aff0cfc2d7)] - **test**: improve punycode coverage to check surrogate pair (Nao YONASHIRO) [#12354](https://github.com/nodejs/node/pull/12354)
- [x] [[`ed130168ed`](https://github.com/nodejs/node/commit/ed130168ed)] - **doc**: add single arg scenario for util.format (Tarun Batra) [#12374](https://github.com/nodejs/node/pull/12374)

**Comment by gibfahn** [comment]
@MylesBorins there were a couple of commits that I wasn't sure about, please review:
- https://github.com/nodejs/node/pull/12334
- https://github.com/nodejs/node/pull/12577 causes a lint failure:

```
/Users/gib/wrk/com/DANGER/node/test/parallel/test-fs-symlink.js
  17:7  error  Unnecessary return statement  no-useless-return

✖ 1 problem (1 error, 0 warnings)
```

**Comment by gibfahn** [comment]
This is done.
