### ISSUE TITLE
backport indentation changes

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/LTS#239]
/cc @Trott 

- [ ] [[`fa8c5f4372`](https://github.com/nodejs/node/commit/fa8c5f4372)] - **tools**: remove legacy indentation linting (Rich Trott) [#14515](https://github.com/nodejs/node/pull/14515)
- [ ] [[`7c51240b1a`](https://github.com/nodejs/node/commit/7c51240b1a)] - **test**: adjust indentation for stricter linting (Rich Trott) [#14431](https://github.com/nodejs/node/pull/14431)
- [ ] [[`a7b3e06e9b`](https://github.com/nodejs/node/commit/a7b3e06e9b)] - **lib**: modify destructuring for indentation (Rich Trott) [#14417](https://github.com/nodejs/node/pull/14417)
- [ ] [[`8010b2148f`](https://github.com/nodejs/node/commit/8010b2148f)] - **lib**: update indentation of ternaries (Rich Trott) [#14247](https://github.com/nodejs/node/pull/14247)
- [ ] [[`4d41502efe`](https://github.com/nodejs/node/commit/4d41502efe)] - **lib**: normalize indentation in parentheses (Rich Trott) [#14125](https://github.com/nodejs/node/pull/14125)
- [ ] [[`d9c3ccac47`](https://github.com/nodejs/node/commit/d9c3ccac47)] - **lib**: remove excess indentation (Rich Trott) [#14090](https://github.com/nodejs/node/pull/14090)
- [ ] [[`a1c342da5b`](https://github.com/nodejs/node/commit/a1c342da5b)] - **lib**: use consistent indentation for ternaries (Rich Trott) [#14078](https://github.com/nodejs/node/pull/14078)

**Comment by Trott** [comment]
Can I do each of these in turn, preserving metadata in the commits, but then submitting one mega-backport PR for them?

**Comment by Trott** [comment]
#10479 should probably happen as well and first. I'll include it in my mega-PR (if it's OK to mega-PR this).

**Comment by Trott** [comment]
#14417 is a no-op when applied to v6.x-staging, so it can be left out.

**Comment by Trott** [comment]
This also needs the ESLint updates for bug fixes.

**Comment by Trott** [comment]
Will need https://github.com/nodejs/node/pull/13950 too.

**Comment by Trott** [comment]
All backported in https://github.com/nodejs/node/pull/14835

**Comment by MylesBorins** [comment]
Lovely!
